[package]
name = "exti-sentry"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "s"

[dependencies]
shield = "0.1"
sentry_uapi = "0.4.1"

[build-dependencies]
outpost_metadata =  "0.1"
